# Generated by Django 3.2.6 on 2021-08-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_try'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
